# Generated by Django 2.1.5 on 2020-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('premium', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
                ('short_desc', models.CharField(max_length=400)),
                ('large_desc', models.TextField()),
            ],
        ),
    ]
